
export const FUNNY_QUOTES = [
  "Confucius say: Man who stand on toilet is high on pot.",
  "The early bird might get the worm, but the second mouse gets the cheese.",
  "I'm not lazy, I'm just on energy saving mode.",
  "My bed is a magical place where I suddenly remember everything I forgot to do.",
  "I don't need a hair stylist, my pillow gives me a new hairstyle every morning.",
  "A day without sunshine is like, you know, night.",
  "I'm on a seafood diet. I see food and I eat it.",
  "If you think you are too small to make a difference, try sleeping with a mosquito.",
  "Change is inevitable, except from a vending machine.",
  "I thought I wanted a career, turns out I just wanted paychecks.",
  "Knowledge is knowing a tomato is a fruit; Wisdom is not putting it in a fruit salad.",
  "If at first you don't succeed, then skydiving isn't for you.",
  "I'm not arguing, I'm just explaining why I'm right.",
  "My wallet is like an onion, opening it makes me cry.",
  "I haven't slept for ten days, because that would be too long.",
  "People say nothing is impossible, but I do nothing every day.",
  "The best thing about the future is that it comes one day at a time.",
  "I find television very educating. Every time someone turns it on, I go into the other room and read a book.",
  "I'm writing a book. I've got the page numbers done.",
  "Everything is funny, as long as it's happening to somebody else.",
  "I'm allergic to stupidity. I break out in sarcasms.",
  "I'm not a complete idiot. Some parts are missing.",
  "Life is short. Smile while you still have teeth.",
  "I don't suffer from insanity. I enjoy every minute of it.",
  "I used to think I was indecisive, but now I'm not so sure.",
  "Experience is what you get when you didn't get what you wanted.",
  "A balanced diet means a cupcake in each hand.",
  "I'm not old, I'm just chronologically gifted.",
  "Common sense is like deodorant. The people who need it most never use it.",
  "I'm not clumsy! The floor just hates me, the table and chairs are bullies, and the wall gets in my way.",
  "If we weren't meant to have midnight snacks, why is there a light in the fridge?",
  "Confucius say: Man who leap off cliff jump to conclusion.",
  "Confucius say: Man who run behind car get exhausted.",
  "Confucius say: Man who run in front of car get tired.",
  "Confucius say: Crowded elevator smell different to midget.",
  "Confucius say: Man who eat many crackers wake up feeling crumb-y.",
  "Confucius say: War does not determine who is right - only who is left.",
  "Confucius say: Man who live in glass house should change clothes in basement.",
  "Confucius say: Man who fart in church sit in own pew.",
  "Confucius say: He who laughs last, didn't get the joke.",
  "Confucius say: Man who push piano down mineshaft get A-flat minor.",
  "Confucius say: Man who smoke pot on top of mountain is high on pot.",
  "Confucius say: Man who keep feet on ground have trouble putting on pants.",
  "\"A wise man once said... nothing at all\" - Jaden",
  "Confucius say: Man who swallow lightbulb burp brilliant idea.",
  "Confucius say: Man who put radio in fridge want cool music.",
  "Confucius say: Man who stand on head have footprints on brain.",
  "Confucius say: Mosquito who bite Iron Man get rusty tongue.",
  "Confucius say: Man who argue with toaster get nothing but crumbs.",
  "Confucius say: Man who paint house with maple syrup have sweet dreams.",
  "Confucius say: Man who eat dictionary go to bed spellbound.",
  "Confucius say: Man who iron shirt while wearing it is pressing his luck.",
  "Confucius say: Man who cross ocean twice without washing is dirty double crosser.",
  "Confucius say: Man who sit on tack get point.",
  "Confucius say: Blind man who eat sandpaper say map is too detailed.",
  "Confucius say: Man who accidentally eat pocket watch have time consuming job.",
  "Confucius say: To trap a tiger, you must first think like a cage.",
  "Confucius say: He who drop watch in toilet bound to have crappy time.",
  "Confucius say: Man who throw dirt is losing ground.",
  "If you try to fail, and succeed, which have you done?",
  "The secret to flying is throwing yourself at the ground and missing.",
  "If a tomato is a fruit, then ketchup is a sports drink.",
  "You can't have your cake and eat it too, unless it's a very small cake and a very big mouth.",
  "If you're riding a horse and it dies, it's best to get off.",
  "Confucius say: Man who jump through screen door strain himself.",
  "Confucius say: Owl who sit on mouse pad is not looking for internet.",
  "To understand the sandwich, you must first become the bread.",
  "Confucius say: Man who sleep inside hollow log wake up feeling board.",
  "Confucius say: Man who put foot in mouth get athlete's tongue.",
  "Confucius say: Man who fight with shadow always tie.",
  "Confucius say: Man who cut himself while shaving lose face.",
  "Confucius say: Man who eat many prunes get good run for money.",
  "Confucius say: Man who sit on hot stove will rise again.",
  "Confucius say: Man who put head in oven get baked.",
  "Confucius say: Man who tell joke to wall get blank stare.",
  "Confucius say: Man who walk in middle of road get run over by both sides.",
  "Confucius say: Man who play with fire make ash of himself.",
  "Confucius say: Man who catch fly with chopsticks accomplish nothing but look cool.",
  "Confucius say: Man who sing in shower ought to be scrubbed.",
  "Confucius say: Man who buy drowned shrub get soaked.",
  "Confucius say: Man who dig hole for another might fall in himself, but at least he got a hole.",
  "Confucius say: Man who argue with mirror never win.",
  "Confucius say: Man who drive like hell bound to get there.",
  "Before you criticize someone, walk a mile in their shoes. That way, you're a mile away and have their shoes.",
  "Never test the depth of the water with both feet.",
  "If you drop a buttered piece of bread on the back of a cat, the universe will explode.",
  "Always remember that you are absolutely unique. Just like everyone else.",
  "The toe you stub today could be the very same toe you stub tomorrow.",
  "A clear conscience is usually just the sign of a bad memory.",
  "If you can't see the bright side of life, polish the dull side.",
  "If you think nobody cares if you're alive, try missing a couple of car payments.",
  "When everything is coming your way, you're probably in the wrong lane.",
  "He who smiles in a crisis has just found someone to blame.",
  "Some people are like clouds. When they disappear, it's a beautiful day.",
  "To be sure of hitting the target, shoot first, and call whatever you hit the target.",
  "Nostalgia isn't what it used to be.",
  "I asked God for a bike, but I know God doesn't work that way. So I stole a bike and asked for forgiveness.",
  "A bank is a place that will lend you money if you can prove that you don't need it.",
  "The best way to appreciate your job is to imagine yourself without one.",
  "A bargain is something you don't need at a price you can't resist.",
  "If God wanted us to fly, He would have given us tickets.",
  "Even a stopped clock is right twice a day. After some years, it can boast of a long series of successes.",
  "If a tree falls in the forest and nobody is there to hear it, it probably still squished a squirrel."
];
